export const SET_CALENDAR_MODE = 'SET_CALENDAR_MODE';
export const SET_CALENDAR_DATE = 'SET_CALENDAR_DATE';

export const ACTIVATE_OVERLAY = 'ACTIVATE_OVERLAY';

export const OPEN_SCHEDULE_MODAL = 'OPEN_SCHEDULE_MODAL';
export const CLOSE_SCHEDULE_MODAL = 'CLOSE_SCHEDULE_MODAL';

export const APPEND_SCHEDULE = 'APPEND_SCHEDULE';
